[window]
decorations = "None"

[colors.bright]
black = "0x7f8490"
blue = "0x76cce0"
cyan = "0xf39660"
green = "0x9ed072"
magenta = "0xb39df3"
red = "0xfc5d7c"
white = "0xe2e2e3"
yellow = "0xe7c664"

[colors.normal]
black = "0x181819"
blue = "0x76cce0"
cyan = "0xf39660"
green = "0x9ed072"
magenta = "0xb39df3"
red = "0xfc5d7c"
white = "0xe2e2e3"
yellow = "0xe7c664"

[colors.primary]
background = "0x2c2e34"
foreground = "0xe2e2e3"

[font]
size = 8

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[env]
TERM = "xterm-256color"
